//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCUT系統開發案.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form
    {
        public string Name { get; set; }
        public string Subject { get; set; }
        public string Kind { get; set; }
        public System.DateTime PickUp_Date { get; set; }
        public string Authorisation_person { get; set; }
        public string Print_Name { get; set; }
        public string Credit { get; set; }
        public byte Print_Num { get; set; }
        public string Print_Side { get; set; }
        public string Print_Size { get; set; }
        public string Memo { get; set; }
        public System.DateTime Apply_Time { get; set; }
    }
}
